In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('C:/Users/ADMIN/Desktop/python jupyter/DATA SCIENCE/CSV FILES/Classification preprocessed data Python.csv')

In [3]:
df.head()

price  resid_area  air_qual  room_num   age  teachers  poor_prop  \
0   24.0       32.31     0.538     6.575  65.2      24.7       4.98   
1   21.6       37.07     0.469     6.421  78.9      22.2       9.14   
2   34.7       37.07     0.469     7.185  61.1      22.2       4.03   
3   33.4       32.18     0.458     6.998  45.8      21.3       2.94   
4   36.2       32.18     0.458     7.147  54.2      21.3       5.33   

   n_hos_beds  n_hot_rooms  rainfall     parks  Sold  avg_dist  airport_YES  \
0       5.480     11.19200        23  0.049347     0    4.0875            1   
1       7.332     12.17280        42  0.046146     1    4.9675            0   
2       7.394     46.19856        38  0.045764     0    4.9675            0   
3       9.268     11.26720        45  0.047151     0    6.0650            1   
4       8.824     11.28960        55  0.039474     0    6.0625            0   

   waterbody_Lake  waterbody_Lake and River  waterbody_River  
0               0                         0                1  
1               1                         0                0  
2               0                         0                0  
3               1                         0                0  
4               1                         0                0

# LOGISTIC REGRESSION

In [4]:
X = df[['price']]
Y = df['Sold']

In [5]:
X.head()

price
0   24.0
1   21.6
2   34.7
3   33.4
4   36.2

In [6]:
Y.head()

0    0
1    1
2    0
3    0
4    0
Name: Sold, dtype: int64

In [7]:
from sklearn.linear_model import LogisticRegression

In [8]:
lr = LogisticRegression()

In [9]:
lr.fit(X,Y)

LogisticRegression()

In [10]:
lr.coef_

array([[-0.03571865]])

In [11]:
lr.intercept_

array([0.61477516])

In [12]:
import statsmodels.api as sn

In [13]:
X_cons = sn.add_constant(X)

In [14]:
X_cons.head()

const  price
0    1.0   24.0
1    1.0   21.6
2    1.0   34.7
3    1.0   33.4
4    1.0   36.2

In [15]:
import statsmodels.discrete.discrete_model as sm

In [16]:
logit = sm.Logit(Y,X_cons).fit()

Optimization terminated successfully.
         Current function value: 0.676690
         Iterations 5


In [17]:
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  506
Model:                          Logit   Df Residuals:                      504
Method:                           MLE   Df Model:                            1
Date:                Thu, 07 Mar 2024   Pseudo R-squ.:                 0.01788
Time:                        11:02:13   Log-Likelihood:                -342.41
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                 0.0004142
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.6149      0.248      2.484      0.013       0.130       1.100
price         -0.0357      0.010     -3.417      0.001      -0.056      -0.015
==============================================================================
"""

# LOGISTIC REGRESSION WITH MULTIPLE PREDICTOR

In [18]:
X = df.loc[:,df.columns != 'Sold']
Y = df['Sold']

In [19]:
lr_mp = LogisticRegression()

In [20]:
lr_mp.fit(X,Y)

LogisticRegression()

In [21]:
lr_mp.coef_

array([[-0.24634681, -0.01729788, -0.11019278,  0.8625383 , -0.00599824,
         0.22821539, -0.21020419,  0.18007874, -0.09088653, -0.00705152,
        -0.00499201, -0.32611862, -0.10520943, -0.09486198, -0.01512214,
         0.20178583]])

In [22]:
lr_mp.intercept_

array([0.01670983])

In [23]:
X_cons = sn.add_constant(X)

In [24]:
logit = sm.Logit(Y,X_cons).fit()

Optimization terminated successfully.
         Current function value: 0.556433
         Iterations 6


In [25]:
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  506
Model:                          Logit   Df Residuals:                      489
Method:                           MLE   Df Model:                           16
Date:                Thu, 07 Mar 2024   Pseudo R-squ.:                  0.1924
Time:                        11:02:13   Log-Likelihood:                -281.56
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                 9.930e-21
============================================================================================
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                       -2.1383      2.649     -0.807      0.420      -7.331       3.054
price                       -0.2741      0.033     -8.313      0.000      -0.339      -0.209
resid_area                   0.0192      0.027      0.720      0.471      -0.033       0.071
air_qual                    -7.4183      2.691     -2.757      0.006     -12.693      -2.144
room_num                     1.1067      0.277      4.001      0.000       0.565       1.649
age                         -0.0020      0.007     -0.302      0.762      -0.015       0.011
teachers                     0.3150      0.064      4.937      0.000       0.190       0.440
poor_prop                   -0.2077      0.034     -6.149      0.000      -0.274      -0.141
n_hos_beds                   0.1760      0.071      2.467      0.014       0.036       0.316
n_hot_rooms                 -0.0742      0.052     -1.439      0.150      -0.175       0.027
rainfall                    -0.0033      0.008     -0.394      0.693      -0.020       0.013
parks                       29.1089     24.177      1.204      0.229     -18.277      76.495
avg_dist                    -0.4017      0.098     -4.118      0.000      -0.593      -0.211
airport_YES                 -0.1524      0.211     -0.723      0.469      -0.565       0.261
waterbody_Lake              -0.1032      0.304     -0.340      0.734      -0.698       0.492
waterbody_Lake and River    -0.0626      0.328     -0.191      0.849      -0.705       0.580
waterbody_River              0.2394      0.256      0.937      0.349      -0.262       0.740
============================================================================================
"""

In [26]:
lr_mp.predict_proba(X)

array([[0.12706304, 0.87293696],
       [0.39755536, 0.60244464],
       [0.98073172, 0.01926828],
       ...,
       [0.2859661 , 0.7140339 ],
       [0.28065305, 0.71934695],
       [0.16347665, 0.83652335]])

In [27]:
Y_pred =lr_mp.predict(X)
Y_pred

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,

In [28]:
Y_pred_01 = (lr_mp.predict_proba(X)[:,1] >= 0.3).astype(bool)

In [29]:
from sklearn.metrics import confusion_matrix

In [30]:
confusion_matrix(Y,Y_pred)

array([[196,  80],
       [ 81, 149]], dtype=int64)

# PERFORMANCE METRICS

# 1) PRECISION : Precision = True positives/ (True positives + False positives)
# 2) RECALL : Recall = True Positive (TP) / True Positive (TP) + False Negative (FN)
# 3) AUC(ROC)

In [31]:
from sklearn.metrics import precision_score,recall_score,accuracy_score

In [32]:
precision_score(Y,Y_pred)

0.6506550218340611

In [33]:
recall_score(Y,Y_pred)

0.6478260869565218

In [34]:
from sklearn.metrics import roc_auc_score

In [35]:
roc_auc_score(Y,Y_pred)

0.6789855072463769

# LINEAR DISCRIMINANT ANALYSIS(LDA)

In [36]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [37]:
clf_lda = LinearDiscriminantAnalysis()

In [38]:
clf_lda.fit(X,Y)

LinearDiscriminantAnalysis()

In [39]:
Y_pred = clf_lda.predict(X)
Y_pred

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,

In [40]:
confusion_matrix(Y,Y_pred)

array([[192,  84],
       [ 79, 151]], dtype=int64)

# KNN

In [41]:
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

In [42]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [43]:
scaler = preprocessing.StandardScaler().fit(X_train)
X_train_s = scaler.transform(X_train)

In [44]:
scaler = preprocessing.StandardScaler().fit(X_test)
X_test_s = scaler.transform(X_test)

In [45]:
from sklearn.neighbors import KNeighborsClassifier

In [46]:
clf_knn = KNeighborsClassifier(n_neighbors=1)
clf_knn.fit(X_train_s,Y_train)

KNeighborsClassifier(n_neighbors=1)

In [47]:
Y_pred = clf_knn.predict(X_test_s)
Y_pred

  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python312\Lib\site-packages\joblib\externals\loky\backend\context.py", line 227, in _count_physical_cores
    cpu_info = subprocess.run(
               ^^^^^^^^^^^^^^^
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


array([1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1], dtype=int64)

In [48]:
confusion_matrix(Y_test,Y_pred)

array([[38, 22],
       [15, 27]], dtype=int64)

In [49]:
accuracy_score(Y_test,Y_pred)

0.6372549019607843

In [50]:
clf_knn1 = KNeighborsClassifier(n_neighbors=3)
clf_knn1.fit(X_train_s,Y_train)

KNeighborsClassifier(n_neighbors=3)

In [51]:
Y_pred = clf_knn1.predict(X_test_s)
Y_pred

array([0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1], dtype=int64)

In [53]:
accuracy_score(Y_test,Y_pred)

0.6078431372549019

In [54]:
from sklearn.model_selection import GridSearchCV

In [55]:
params = {'n_neighbors':[1,2,3,4,5,6,7,8,9,10]}

In [56]:
grid_search_cv = GridSearchCV(KNeighborsClassifier(),params)

In [57]:
grid_search_cv.fit(X_train_s,Y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]})

In [59]:
grid_search_cv.best_params_

{'n_neighbors': 4}

In [60]:
optimised_knn = grid_search_cv.best_estimator_

In [62]:
Y_pred = optimised_knn.predict(X_test_s)
Y_pred

array([0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0], dtype=int64)

In [63]:
confusion_matrix(Y_test,Y_pred)

array([[44, 16],
       [27, 15]], dtype=int64)

In [64]:
accuracy_score(Y_test,Y_pred)

0.5784313725490197