## SVR BASED REGRESSION MODEL

In [51]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('C:/Users/ADMIN/Desktop/python jupyter/DATA SCIENCE/CSV FILES/Movie_regression.csv')

In [3]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  
0          223.840  Thriller              23            494       48000  
1          243.456     Drama              42            462       43200  
2         2022.400    Comedy              38            458       69400  
3          225.344     Drama              45            472       66800  
4          225.792     Drama              55            395       72400

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           494 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

In [5]:
df['Time_taken'].mean()

157.3914979757085

In [6]:
df['Time_taken'].fillna(value=df['Time_taken'].mean(),inplace=True)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           506 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

In [8]:
df = pd.get_dummies(df,columns = ["3D_available","Genre"],drop_first=True)

In [9]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views  Time_taken  Twitter_hastags  \
0            7.995           7.94         527367      109.60          223.840   
1            7.470           7.44         494055      146.64          243.456   
2            7.515           7.44         547051      147.88         2022.400   
3            7.020           8.26         516279      185.36          225.344   
4            7.070           8.26         531448      176.48          225.792   

   Avg_age_actors  Num_multiplex  Collection  3D_available_YES  Genre_Comedy  \
0              23            494       48000              True         False   
1              42            462       43200             False         False   
2              38            458       69400             False          True   
3              45            472       66800              True         False   
4              55            395       72400             False         False   

   Genre_Drama  Genre_Thriller  
0        False            True  
1         True           False  
2        False           False  
3         True           False  
4         True           False

In [10]:
X = df.loc[:,df.columns!="Collection"]
Y = df['Collection']

In [14]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

## Standardizing Data
### https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
sc = StandardScaler().fit(X_train)

In [17]:
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

In [18]:
X_train_std

array([[ 1.28770177,  1.03323679, -0.48925206, ..., -0.66547513,
         1.98162289, -0.74420841],
       [-0.33638447, -0.41315956,  0.15723342, ..., -0.66547513,
        -0.50463688,  1.34370962],
       [-0.40325332, -0.71521823,  1.00872286, ...,  1.50268577,
        -0.50463688, -0.74420841],
       ...,
       [-0.40547014, -1.30336132,  1.03339138, ...,  1.50268577,
        -0.50463688, -0.74420841],
       [ 0.85189733,  1.03323679, -1.56105695, ..., -0.66547513,
        -0.50463688, -0.74420841],
       [-0.38135592, -0.35216694,  0.31034841, ..., -0.66547513,
        -0.50463688, -0.74420841]])

In [19]:
X_test_std

array([[-0.39680933, -1.00711147,  0.39541229, ...,  1.50268577,
        -0.50463688, -0.74420841],
       [-0.40079621, -0.66439105,  0.93131473, ..., -0.66547513,
        -0.50463688,  1.34370962],
       [-0.39523443,  2.43316256, -0.44672012, ...,  1.50268577,
        -0.50463688, -0.74420841],
       ...,
       [ 1.1779666 ,  1.03323679, -0.34464347, ...,  1.50268577,
        -0.50463688, -0.74420841],
       [-0.40131065, -0.94321444,  0.91430195, ..., -0.66547513,
        -0.50463688,  1.34370962],
       [-0.39643252,  0.26792466,  1.01637861, ...,  1.50268577,
        -0.50463688, -0.74420841]])

## training a regression tree
### https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVR.html

In [27]:
from sklearn.svm import SVR
svr = SVR(kernel='linear',C=5000)

In [28]:
svr.fit(X_train_std,Y_train)

SVR(C=5000, kernel='linear')

In [29]:
Y_pred = svr.predict(X_test_std)
Y_pred

array([53081.17956628, 62305.37306863, 30734.9758036 , 46690.94284526,
       37075.10524801, 47233.7302387 , 32213.89959109, 34816.03306393,
       38581.23224324, 42990.69911501, 38603.72141631, 32730.69364039,
       -7688.47069021, 48652.11253393, 37382.22207163, 51138.90433544,
       34425.44511276,  6984.58283864, 79052.66221155, 34227.29125462,
       53463.67468939, 59544.1794348 , 26133.09762085, 50359.00003671,
       34701.55843024, 28117.8966836 , 42277.04223705, 36500.35361901,
       37645.06423533, 38094.29003763, 36060.37755653, 53417.3009261 ,
       53027.38614419, 25998.67289856, 30084.60529706, 29948.21255504,
       51957.77164805, 39277.0410969 , 39384.08478771, 55153.47115319,
       27479.33005459, 60198.34081716, 76962.37235307, 35149.6761768 ,
       58686.60545763, 29108.99421197, 31564.07323909, 53324.31012115,
       36634.61047925, 55833.61038409, 35661.23867866, 67702.62068126,
       35195.70259144, 59589.86002538, 77699.16818815, 43079.60741587,
      

## model performance

In [30]:
from sklearn.metrics import mean_squared_error,r2_score

In [31]:
mean_squared_error(Y_test,Y_pred)

128152271.09429798

In [32]:
r2_score(Y_test,Y_pred)

0.565551713456417

# SVM BASED CLASSIFICATION MODEL

In [33]:
df = pd.read_csv('C:/Users/ADMIN/Desktop/python jupyter/DATA SCIENCE/CSV FILES/Movie_classification.csv')

In [34]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  \
0          223.840  Thriller              23            494       48000   
1          243.456     Drama              42            462       43200   
2         2022.400    Comedy              38            458       69400   
3          225.344     Drama              45            472       66800   
4          225.792     Drama              55            395       72400   

   Start_Tech_Oscar  
0                 1  
1                 0  
2                 1  
3                 1  
4                 1

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           494 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

In [36]:
df['Time_taken'].mean()

157.3914979757085

In [37]:
df['Time_taken'].fillna(value=df['Time_taken'].mean(),inplace=True)

In [38]:
df = pd.get_dummies(df,columns = ["3D_available","Genre"],drop_first=True)

In [39]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  ...  Time_taken  Twitter_hastags  \
0            7.995           7.94  ...      109.60          223.840   
1            7.470           7.44  ...      146.64          243.456   
2            7.515           7.44  ...      147.88         2022.400   
3            7.020           8.26  ...      185.36          225.344   
4            7.070           8.26  ...      176.48          225.792   

   Avg_age_actors  Num_multiplex  Collection  Start_Tech_Oscar  \
0              23            494       48000                 1   
1              42            462       43200                 0   
2              38            458       69400                 1   
3              45            472       66800                 1   
4              55            395       72400                 1   

   3D_available_YES  Genre_Comedy  Genre_Drama  Genre_Thriller  
0              True         False        False            True  
1             False         False         True           False  
2             False          True        False           False  
3              True         False         True           False  
4             False         False         True           False  

[5 rows x 21 columns]

In [42]:
X = df.drop(['Start_Tech_Oscar'],axis=1)
Y = df['Start_Tech_Oscar']

In [43]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [44]:
sc = StandardScaler().fit(X_train)

In [45]:
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

In [46]:
X_train_std

array([[ 1.28770177,  1.03323679, -0.48925206, ..., -0.66547513,
         1.98162289, -0.74420841],
       [-0.33638447, -0.41315956,  0.15723342, ..., -0.66547513,
        -0.50463688,  1.34370962],
       [-0.40325332, -0.71521823,  1.00872286, ...,  1.50268577,
        -0.50463688, -0.74420841],
       ...,
       [-0.40547014, -1.30336132,  1.03339138, ...,  1.50268577,
        -0.50463688, -0.74420841],
       [ 0.85189733,  1.03323679, -1.56105695, ..., -0.66547513,
        -0.50463688, -0.74420841],
       [-0.38135592, -0.35216694,  0.31034841, ..., -0.66547513,
        -0.50463688, -0.74420841]])

In [47]:
X_test_std

array([[-0.39680933, -1.00711147,  0.39541229, ...,  1.50268577,
        -0.50463688, -0.74420841],
       [-0.40079621, -0.66439105,  0.93131473, ..., -0.66547513,
        -0.50463688,  1.34370962],
       [-0.39523443,  2.43316256, -0.44672012, ...,  1.50268577,
        -0.50463688, -0.74420841],
       ...,
       [ 1.1779666 ,  1.03323679, -0.34464347, ...,  1.50268577,
        -0.50463688, -0.74420841],
       [-0.40131065, -0.94321444,  0.91430195, ..., -0.66547513,
        -0.50463688,  1.34370962],
       [-0.39643252,  0.26792466,  1.01637861, ...,  1.50268577,
        -0.50463688, -0.74420841]])

## training svm : kernel = linear
### https://scikit-learn.org/stable/modules/svm.html

In [48]:
from sklearn import svm

In [49]:
clf_svm = svm.SVC(kernel='linear',C=0.01)
clf_svm.fit(X_train_std,Y_train)

SVC(C=0.01, kernel='linear')

In [50]:
Y_pred = clf_svm.predict(X_test_std)
Y_pred

array([1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [52]:
confusion_matrix(Y_test,Y_pred)

array([[10, 32],
       [ 6, 54]], dtype=int64)

In [53]:
accuracy_score(Y_test,Y_pred)

0.6274509803921569

In [54]:
clf_svm.n_support_

array([188, 192])

## kernel = polynomial

In [67]:
clf_svm_poly = svm.SVC(kernel='poly',degree=2,C=0.01)
clf_svm_poly.fit(X_train_std,Y_train)

SVC(C=0.01, degree=2, kernel='poly')

In [70]:
Y_pred = clf_svm_poly.predict(X_test_std)
Y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [65]:
confusion_matrix(Y_test,Y_pred)

array([[31, 11],
       [23, 37]], dtype=int64)

In [71]:
accuracy_score(Y_test,Y_pred)

0.5882352941176471

In [72]:
clf_svm_poly.n_support_

array([188, 192])

## kernel = radial

In [73]:
clf_svm_rad = svm.SVC(kernel='rbf',gamma=0.5,C=10)
clf_svm_rad.fit(X_train_std,Y_train)

SVC(C=10, gamma=0.5)

In [74]:
Y_pred = clf_svm_rad.predict(X_test_std)
Y_pred

array([0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1], dtype=int64)

In [75]:
confusion_matrix(Y_test,Y_pred)

array([[19, 23],
       [12, 48]], dtype=int64)

In [76]:
accuracy_score(Y_test,Y_pred)

0.6568627450980392

In [78]:
clf_svm_rad.n_support_

array([188, 216])

# HYPERPARAMETER TUNING
## Linear GRID SEARCH CV

In [55]:
from sklearn.model_selection import GridSearchCV 

In [56]:
params = {'C':(0.001,0.005,0.01,0.05,0.1,0.5,1,5,10,50,100,500,1000)}

In [58]:
clf_svm1 = svm.SVC(kernel='linear')

In [59]:
svm_grid_lin = GridSearchCV(clf_svm1,params,n_jobs=-1,cv=10,verbose=1,scoring='accuracy')

In [60]:
svm_grid_lin.fit(X_train_std,Y_train)

Fitting 10 folds for each of 13 candidates, totalling 130 fits


GridSearchCV(cv=10, estimator=SVC(kernel='linear'), n_jobs=-1,
             param_grid={'C': (0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50,
                               100, 500, 1000)},
             scoring='accuracy', verbose=1)

In [61]:
svm_grid_lin.best_params_

{'C': 1}

In [62]:
lin_svm_clf = svm_grid_lin.best_estimator_

In [64]:
Y_pred = lin_svm_clf.predict(X_test_std)
Y_pred

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0], dtype=int64)

In [65]:
confusion_matrix(Y_test,Y_pred)

array([[31, 11],
       [23, 37]], dtype=int64)

In [66]:
accuracy_score(Y_test,Y_pred)

0.6666666666666666

## Radial Grid Search CV

In [79]:
params = {"C":(0.01,0.05,0.1,0.5,1,5,10,50),
         "gamma":(0.001,0.01,0.1,1)}

In [81]:
clf_svm2 = svm.SVC(kernel='rbf')

In [82]:
svm_grid_rad = GridSearchCV(clf_svm2,params,n_jobs=-1,cv=10,verbose=1,scoring='accuracy')

In [83]:
svm_grid_rad.fit(X_train_std,Y_train)

Fitting 10 folds for each of 32 candidates, totalling 320 fits


GridSearchCV(cv=10, estimator=SVC(), n_jobs=-1,
             param_grid={'C': (0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50),
                         'gamma': (0.001, 0.01, 0.1, 1)},
             scoring='accuracy', verbose=1)

In [84]:
svm_grid_rad.best_params_

{'C': 5, 'gamma': 0.01}

In [85]:
rad_svm_clf = svm_grid_rad.best_estimator_

In [86]:
Y_pred = rad_svm_clf.predict(X_test_std)
Y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0], dtype=int64)

In [87]:
confusion_matrix(Y_test,Y_pred)

array([[31, 11],
       [26, 34]], dtype=int64)

In [88]:
accuracy_score(Y_test,Y_pred)

0.6372549019607843

## polynomial Grid Search CV

In [89]:
params = {"C":(0.01,0.05,0.1,0.5,1,5,10,50),
         "degree":(1,2,3,4,5)}

In [90]:
clf_svm3 = svm.SVC(kernel='rbf')

In [91]:
svm_grid_poly = GridSearchCV(clf_svm3,params,n_jobs=-1,cv=10,verbose=1,scoring='accuracy')

In [92]:
svm_grid_poly.fit(X_train_std,Y_train)

Fitting 10 folds for each of 40 candidates, totalling 400 fits


GridSearchCV(cv=10, estimator=SVC(), n_jobs=-1,
             param_grid={'C': (0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50),
                         'degree': (1, 2, 3, 4, 5)},
             scoring='accuracy', verbose=1)

In [93]:
svm_grid_poly.best_params_

{'C': 1, 'degree': 1}

In [96]:
poly_svm_clf = svm_grid_poly.best_estimator_

In [97]:
Y_pred = poly_svm_clf.predict(X_test_std)
Y_pred

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0], dtype=int64)

In [98]:
confusion_matrix(Y_test,Y_pred)

array([[30, 12],
       [21, 39]], dtype=int64)

In [99]:
accuracy_score(Y_test,Y_pred)

0.6764705882352942